grammar Base;

ID : [a-z]+;

literal : INT_LITERAL | FLOAT_LITERAL | SCIENTIFIC_FLOAT_LITERAL | STRING_LITERAL | BOOL_LITERAL | NULL_LITERAL;

INT_LITERAL : [0-9]+;
SCIENTIFIC_FLOAT_LITERAL : FLOAT_LITERAL 'e' INT_LITERAL | INT_LITERAL 'e' INT_LITERAL;
FLOAT_LITERAL : ([0-9]+ '.' [0-9]*) | ([0-9]* '.' [0-9]+);
STRING_LITERAL : '"' .*? '"';
BOOL_LITERAL : 'true' | 'false';
NULL_LITERAL : 'null';